### PR TITLE
Fix Details Screens Issues (Movie, Series, Cast, Recommended, YoutubePlayer, Seasons)

### LINKED ISSUE #662: Cast Details : When no Internet not presented properly
[Image](https://github.com/user-attachments/assets/78138a58-f412-40f0-ae10-afb00eb9dbe2)

### LINKED ISSUE #663: Movie & Series Details : Wrong Bottom Padding
Image

### LINKED ISSUE #664: Movie Details : Date Format in Movie Details Screen is different from design
Image

### LINKED ISSUE #665: Movie Details : Clipped Circular Progress Bar when add movie to collection
https://github.com/user-attachments/assets/164f4ecb-c7cf-473a-87ce-7c90cdb70cdd

### LINKED ISSUE #667: Video Screen : Wrong Padding
Image

### LINKED ISSUE #668: Video Screen : No Internet State Not Handled Properly
Image

### LINKED ISSUE #670: Movie & Series Details : When Add Rating to the Movie or Series it have to be presented in the Details Screen
Image
Image

### LINKED ISSUE #686: Seasons Screen Crashes Immediatly

### LINKED ISSUE #687: Recommended Series Screen wrong horizontal padding

### PR DESCRIPTION
**Pull request by dev-bilal-azzam**
1. https://github.com/Rome-Squad/CineVerse-App/issues/662
2. https://github.com/Rome-Squad/CineVerse-App/issues/663
3. https://github.com/Rome-Squad/CineVerse-App/issues/664
4. https://github.com/Rome-Squad/CineVerse-App/issues/665
5. https://github.com/Rome-Squad/CineVerse-App/issues/667
6. https://github.com/Rome-Squad/CineVerse-App/issues/668
7. https://github.com/Rome-Squad/CineVerse-App/issues/686
8. https://github.com/Rome-Squad/CineVerse-App/issues/687
9. https://github.com/Rome-Squad/CineVerse-App/issues/670

### CODE REVIEW

**Review by Mohamed-Ashraf-2210 — DISMISSED** [review]

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/seasons/SeasonsViewModel.kt [hunk 1]
```diff
@@ -39,17 +40,19 @@ class SeasonsViewModel @Inject constructor(
         }
     }
 
-    private fun loadSeasonsSuccess(season: List<Season>) {
+    private fun loadSeasonsSuccess(seasons: List<Season>) {
+        Log.d("SeasonsViewModel", "loadSeasonsSuccess: $seasons")
```
Comment (HendSayed25) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/seasons/SeasonsViewModel.kt]: remove this Log

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/seasons/SeasonsViewModel.kt [hunk 2]
```diff
@@ -39,17 +40,19 @@ class SeasonsViewModel @Inject constructor(
...
-                seasons = season.map(Season::toUi),
+                seasons = seasons.map(Season::toUi),
                 isLoading = false,
                 isNoInternet = false
             )
         }
     }
 
     private fun loadSeasonsError(error: Throwable) {
+        Log.d("SeasonsViewModel", "loadSeasonsError: $error")
```
Comment (HendSayed25) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/seasons/SeasonsViewModel.kt]: and this

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]

**Review by skaik-mo — APPROVED** [review]
