### PR TITLE
Fix/269 handle loading and no results UI states

### LINKED ISSUE #269: Handle Loading and No Results UI States
https://github.com/user-attachments/assets/ed7160c5-ca5b-4f1a-8669-ebb9891b3a73

### PR DESCRIPTION
**Pull request by poula22**
- fix get recent poster bug when back from search result
- add cast to recent viewed.
- add navigation logic to poster details when any poster clicked
- add clear all recent viewed
- fix recent viewed bug with local data source: make insert strategy Ignore
- add loading to search result
- fix ui bugs and make search screen ui matches figma 100%

https://github.com/user-attachments/assets/0b27759c-87ff-40e6-b510-28332e9b5be7

### CODE REVIEW

File: presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsViewModel.kt [hunk 1]
```diff
@@ -70,18 +138,29 @@ class SeriesDetailsViewModel(
...
                 isLoading = false
             )
         }
         loadSeriesGenres(series.genreIDs)
+        saveSeriesToRecent(series)
+    }
+
+    private fun saveSeriesToRecent(series: Series) {
+        safeExecute(
+            onError = { Log.i("dsdssd erererror", it.message.toString()) },
```
Comment (mohannadahmed00) [inline presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsViewModel.kt:155]: remove these logs

File: presentation/explore/src/main/java/com/giraffe/explore/components/ExploreHeader.kt [hunk 2]
```diff
@@ -44,6 +47,7 @@ fun ExploreHeader(
     value: String = "",
     readOnly: Boolean = false,
     focusRequester: FocusRequester = FocusRequester(),
+    onSearch: () -> Unit = {},
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/components/ExploreHeader.kt:50]: why did you add it? it already has onSearchClick!!

File: presentation/explore/src/main/java/com/giraffe/explore/screen/discover/DiscoverScreen.kt [hunk 3]
```diff
@@ -125,13 +128,12 @@ private fun GenresAndCardsSection(
             .fillMaxWidth()
             .background(Theme.color.background.screen)
     ) {
-        //TODO
-        /*TransitionLazyColumnToGrid(
+        TransitionLazyColumnToGrid(
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/screen/discover/DiscoverScreen.kt:131]: why did you uncomment it?? i'm working on it and i already set it as TODO

**Review by mahmmedn19 — APPROVED** [review]
good

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchInteractionListener.kt [hunk 4]
```diff
@@ -1,10 +1,12 @@
 package com.giraffe.explore.screen.search
 
 interface SearchInteractionListener {
+    fun getRecentViewedPoster()
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchInteractionListener.kt:4]: this is not an interaction. this can be invoked silently in init block of viewmodel.

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt [hunk 5]
```diff
@@ -36,14 +41,24 @@ import org.koin.androidx.compose.koinViewModel
 fun SearchScreen(
     navigateToSearchResult: (String) -> Unit,
     onBackClick: () -> Unit,
+    onClickPoster: (Poster) -> Unit,
     viewModel: SearchViewModel = koinViewModel(),
 ) {
-    val state by viewModel.state.collectAsState()
+    val state by viewModel.state.collectAsStateWithLifecycle()
+    val lifecycle = LocalLifecycleOwner.current
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt:48]: remove it. it should be handled in viewmodel

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchViewModel.kt [hunk 6]
```diff
@@ -6,35 +6,42 @@ import com.giraffe.media.explore.usecase.ClearSearchHistoryUseCase
...
+    private val clearRecentlyPeopleUseCase: ClearRecentPeopleUseCase
 ) : BaseViewModel<SearchScreenState>(SearchScreenState()),
     SearchInteractionListener {
     init {
-        getRecentViewedPoster()
         onQueryChange()
     }
 
-    private fun getRecentViewedPoster() {
+    override fun getRecentViewedPoster() {
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchViewModel.kt:38]: it is not needed to access it outside the viewmodel

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]
Great job

**Review by mohannadahmed00 — APPROVED** [review]

**Review by skaik-mo — APPROVED** [review]
Approve depends on the approve of Mohammed Nasser
