### PR TITLE
Fix recording in search result screen

### LINKED ISSUE #655: Recording in sreach
- The microphone not working while text field has text , we need to enable recording although the text field contains text 

https://github.com/user-attachments/assets/6f3fe058-3343-40fa-8911-593685bdf0db

### PR DESCRIPTION
**Pull request by HendSayed25**
# What's Updated ?

- Now when click to microphone icon in search result screen the Recording will work well by navigate to search screen and start recording .
- Text Field value is constantly changing with external change.

### CODE REVIEW

File: designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt [hunk 1]
```diff
@@ -104,6 +104,15 @@ fun DefaultTextField(
         )
     }
 
+    LaunchedEffect(value) {
```
Comment (mohannadahmed00) [inline designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt]: you can just add a state to the remember of textFieldValue  like that "remember(value)" and it will be updated, so you can remove the LaunchedEffect

**Review by mohannadahmed00 — CHANGES_REQUESTED** [review]

**Review by mohannadahmed00 — APPROVED** [review]

**Review by mohamedebrahem13 — APPROVED** [review]
