### PR TITLE
Fix authentication bugs phase 2

### LINKED ISSUE #485: Login Bugs
# Should Handle :

- create a new account top padding should be replaced with bottom padding 24.dp [Done]
- If user is logged in we should start from home graph. [Done]
- when join as guest remove static name "Ashraf " from home [Done]
- webview should be restricted to reset password in website only [Done]
- add loading state instead of white screen when navigate to web view to reset password [Done]

### PR DESCRIPTION
**Pull request by HendSayed25**
This PR solved the following :
1- Login Bugs :

- If user is logged in we should start from home graph not from login screen. 
- when join as guest remove static name "Ashraf " from home 
- webview should be restricted to reset password in website only 
- add loading state instead of white screen when navigate to web view to reset password 

2- Adding Main View Model For Main Activity For handle states of if user logged before or not and to handle onboarding

### CODE REVIEW

File: app/src/main/java/com/giraffe/cineverseapp/main_activity/MainActivity.kt [hunk 1]
```diff
@@ -0,0 +1,51 @@
+package com.giraffe.cineverseapp.main_activity
```
Comment (devfalah) [inline app/src/main/java/com/giraffe/cineverseapp/main_activity/MainActivity.kt]: rename the package to `main`

```suggestion
package com.giraffe.cineverseapp.main
```

File: app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt [hunk 2]
```diff
@@ -0,0 +1,6 @@
+package com.giraffe.cineverseapp.main_activity
+
+data class MainUiState(
+    val isLoggedIn: Boolean? = null,
```
Comment (devfalah) [inline app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt]: why is this nullable?

File: app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt [hunk 3]
```diff
@@ -0,0 +1,6 @@
...
+    val isOnBoardingFirstTime: Boolean? = null,
```
Comment (devfalah) [inline app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt]: same

File: app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt (hunk 2 above)
Comment (devfalah) [reply app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt]: we need to make it non-nullable

File: app/src/main/java/com/giraffe/cineverseapp/main_activity/MainViewModel.kt [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+                    isOnBoardingFirstTime = result,
+                )
+            }
+        ) {
+            isOnBoardingFirstTimeUseCase()
+        }
+    }
+
+
+    fun checkIsLoggedIn() {
```
Comment (devfalah) [inline app/src/main/java/com/giraffe/cineverseapp/main_activity/MainViewModel.kt]: should be private methods

File: app/src/main/java/com/giraffe/cineverseapp/main_activity/MainViewModel.kt [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+    }
+
+
+    fun checkIfOnBoardingFirstTime() {
+        safeExecute(
+            onSuccess = { result ->
+                _state.value = _state.value.copy(
+                    isOnBoardingFirstTime = result,
+                )
+            }
```
Comment (devfalah) [inline app/src/main/java/com/giraffe/cineverseapp/main_activity/MainViewModel.kt]: you can create a method for success case like:

```suggestion
              onSuccess = ::onCheckOnBoardingFirstTimeSuccess
```

File: app/src/main/java/com/giraffe/cineverseapp/main_activity/MainViewModel.kt [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+        ) {
+            isOnBoardingFirstTimeUseCase()
+        }
+    }
+
+
+    fun checkIsLoggedIn() {
+        safeExecute(
+            onSuccess = { result ->
+                _state.value = _state.value.copy(
```
Comment (devfalah) [inline app/src/main/java/com/giraffe/cineverseapp/main_activity/MainViewModel.kt]: same

**Review by devfalah — DISMISSED** [review]

File: app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt (hunk 2 above)
Comment (HendSayed25) [reply app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt]: Because I want to handle the splash screen duration to display it for a while until the status changes, whether it becomes false or true, so I can determine if it should go to the login or not, to avoid the problem of it going to the login until the status changes.

Comment (HendSayed25) [reply app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt:4]: Screenshot 2025-08-04 191805

**Review by Mostafa-khaled21 — APPROVED** [review]

File: app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt (hunk 2 above)
Comment (HendSayed25) [reply app/src/main/java/com/giraffe/cineverseapp/main_activity/MainUiState.kt]: Screenshot 2025-08-04 193651

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]
