### PR TITLE
 Fix Placeholder in Cast on Details and Actor Search Screens

### LINKED ISSUE #241: Fix Placeholder in Cast on Details and Actor Search Screens
The placeholder images or content in the Cast section on both the Details Screen and the Actor Search Screen are not displaying correctly or look inconsistent.

Image

Image

### PR DESCRIPTION
**Pull request by skaik-mo**
- Modify `PersonCacheDto.toEntity`, `Person.toDto`, `PersonDto.toEntity`, `CastDto.toEntity`, `CrewDto.toEntity`, and `PersonCreditDto.toEntity` to handle potential null image URLs by checking if the URL already contains `BASE_IMAGE_URL` before prepending it.
- In `SafeIslamicImage`, check if `imageUrl` is blank or "null" and set `isPlaceholder` to true accordingly to prevent loading issues.
- Update `StarCastSection` and `CastItem` to display an icon placeholder when the image URL is null or empty.
- Delete the `ResultsActors` composable as it is no longer used.

image

image

### CODE REVIEW

**Review by Ashraf-El-Fallah — DISMISSED** [review]

File: presentation/details/src/main/java/com/giraffe/details/components/StarCastSection.kt [hunk 1]
```diff
@@ -115,7 +118,17 @@ fun CastCard(
                         )
                     ),
                 contentScale = ContentScale.Crop
-            )
+            ) {
+                Icon(
+                    painter = painterResource(Theme.icons.dueTone.image),
+                    contentDescription = null,
```
Comment (Mohamed-Ashraf-2210) [inline presentation/details/src/main/java/com/giraffe/details/components/StarCastSection.kt]: add content description

**Review by Mohamed-Ashraf-2210 — DISMISSED** [review]

**Review by AhmedMohamed056 — DISMISSED** [review]

**Review by Ashraf-El-Fallah — DISMISSED** [review]

**Review by Mohamed-Ashraf-2210 — DISMISSED** [review]

**Review by mohannadahmed00 — DISMISSED** [review]

File: imageviewer/src/main/java/com/giraffe/imageviewer/component/SafeIslamicImage.kt [hunk 2]
```diff
@@ -66,6 +66,10 @@ fun SafeIslamicImage(
     var shouldBlur by remember { mutableStateOf(true) }
     LaunchedEffect(imageUrl) {
         isPlaceholder = true
+        if (imageUrl.isBlank() || imageUrl == "null") {
+            isPlaceholder = true
```
Comment (dev-bilal-azzam) [inline imageviewer/src/main/java/com/giraffe/imageviewer/component/SafeIslamicImage.kt]: no need

**Review by dev-bilal-azzam — DISMISSED** [review]

File: presentation/details/src/main/java/com/giraffe/details/components/StarCastSection.kt [hunk 3]
```diff
@@ -115,7 +118,17 @@ fun CastCard(
...
                 contentScale = ContentScale.Crop
-            )
+            ) {
+                Icon(
+                    painter = painterResource(Theme.icons.dueTone.image),
+                    contentDescription = "$actorName image",
+                    tint = Theme.color.brand.secondary,
+                    modifier = it
+                        .size(64.dp)
+                        .size(28.dp)
```
Comment (mohamedebrahem13) [inline presentation/details/src/main/java/com/giraffe/details/components/StarCastSection.kt]: Why you are using size twice?

File: presentation/explore/src/main/java/com/giraffe/explore/components/CastItem.kt [hunk 4]
```diff
@@ -42,7 +46,23 @@ fun CastItem(
...
+                tint = Theme.color.brand.secondary,
+                modifier = it
+                    .fillMaxWidth()
+                    .aspectRatio(1f)
+                    .background(
+                        Theme.color.background.card,
+                        shape = RoundedCornerShape(Theme.radius.lg)
+                    )
+                    .size(28.dp)
+                    .wrapContentSize(),
```
Comment (mohamedebrahem13) [inline presentation/explore/src/main/java/com/giraffe/explore/components/CastItem.kt:61]: I think You don't need Wrap content size because you give size before it

**Review by mohamedebrahem13 — CHANGES_REQUESTED** [review]
You need to remove some extra modifiers

**Review by Ashraf-El-Fallah — DISMISSED** [review]

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]

**Review by mohamedebrahem13 — APPROVED** [review]

**Review by mohannadahmed00 — APPROVED** [review]

**Review by dev-bilal-azzam — APPROVED** [review]
