### PR TITLE
fix: Update search text field to use TextFieldValue for better cursor management

### LINKED ISSUE #354: Fix cursor of search text field in search screen
when request focus to text field of search it appears at start of text, but It should appear at end of text.

### PR DESCRIPTION
**Pull request by Mostafa-khaled21**
Fixes Cursor Position on Focus: The cursor now correctly moves to the end of the text when the field is focused or when its value is updated programmatically.

Corrects RTL Typing: Resolves a bug where the cursor would jump to the wrong position while typing in RTL languages like Arabic.

Improves State Management: The component's internal state was switched from String to TextFieldValue to allow for precise control over text selection and cursor behavior.

https://github.com/user-attachments/assets/11b44176-27ce-4a27-a765-7150b1c12029

### CODE REVIEW

**Review by HendSayed25 — DISMISSED** [review]
👏

File: designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt [hunk 1]
```diff
@@ -142,14 +152,19 @@ fun DefaultTextField(
...
+                value = textFieldValue,
                 maxLines = maxLines,
                 singleLine = singleLine,
-                onValueChange = {
-                    Log.i("maxCharacters", it.length.toString())
-                    if (it.length <= maxCharacters) {
-                        if (it.contains("\n")) onValueChange(it.replace("\n", " "))
-                        else onValueChange(it)
+                onValueChange = { newValue ->
+                    Log.i("maxCharacters", newValue.text.length.toString())
```
Comment (mohannadahmed00) [inline designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt]: remove this log

**Review by mohannadahmed00 — DISMISSED** [review]

**Review by HendSayed25 — APPROVED** [review]

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]

**Review by dev-bilal-azzam — APPROVED** [review]

**Review by poula22 — APPROVED** [review]
Great Job 👏🔥
