### PR TITLE
Fix/details screen null data

### LINKED ISSUE #297: Issue: Movie details has issue on loading data and date appears as null
Image

### PR DESCRIPTION
**Pull request by Mohamed-Ashraf-2210**
fix details screen null data
refactor spacer issues in details screen
remove space and padding make a ui issues in staff info section

Screenshot_20250731_150901_CineVerse App

### CODE REVIEW

**Review by Mostafa-khaled21 — APPROVED** [review]

**Review by mohannadahmed00 — APPROVED** [review]

File: presentation/details/src/main/java/com/giraffe/details/components/StaffInfoSection.kt [hunk 1]
```diff
@@ -53,7 +51,7 @@ fun StaffInfoSection(
                 modifier = Modifier.fillMaxWidth(),
                 shape = RoundedCornerShape(Theme.radius.lg),
             ) {
-                Column(modifier = Modifier.padding(vertical = 8.dp)) {
+                Column {
                     staffList.entries.toList().forEachIndexed { index, (key, value) ->
```
Comment (mohamedebrahem13) [inline presentation/details/src/main/java/com/giraffe/details/components/StaffInfoSection.kt:55]: I think there is compile error here with ">"

File: presentation/details/src/main/java/com/giraffe/details/models/MovieUi.kt [hunk 2]
```diff
@@ -23,10 +23,10 @@ fun Movie.toMovieUi() = MovieUi(
     title = title,
     description = description,
     rating = rating,
-    duration = duration?.toFormattedDuration(),
+    duration = if (duration != null && duration!! > 0) duration?.toFormattedDuration() else null,
```
Comment (mohamedebrahem13) [inline presentation/details/src/main/java/com/giraffe/details/models/MovieUi.kt:26]: extra check here !!

Comment (Mohamed-Ashraf-2210) [reply presentation/details/src/main/java/com/giraffe/details/models/MovieUi.kt:26]: it is handel crash

File: presentation/details/src/main/java/com/giraffe/details/components/StaffInfoSection.kt (hunk 1 above)
Comment (Mohamed-Ashraf-2210) [reply presentation/details/src/main/java/com/giraffe/details/components/StaffInfoSection.kt:55]: i think no

File: presentation/details/src/main/java/com/giraffe/details/models/MovieUi.kt (hunk 2 above)
Comment (skaik-mo) [reply presentation/details/src/main/java/com/giraffe/details/models/MovieUi.kt:26]: why use !! here `duration!! > 0`

**Review by AhmedMohamed056 — APPROVED** [review]

File: presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/screen/MovieDetailsScreen.kt [hunk 3]
```diff
@@ -170,48 +170,57 @@ private fun MovieDetailsContent(
...
             RatingSection(
                 modifier = Modifier.padding(horizontal = 16.dp),
                 onClickCard = interaction::onGiveStarsClick
             )
         }
-        item {
-
-            AnimatedVisibility(state.movieReviews.isNotEmpty()) {
 
+        if (state.movieReviews.isNotEmpty()) {
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/details/screens/moviedetails/screen/MovieDetailsScreen.kt:222]: Use AnimatedVisibility

**Review by skaik-mo — APPROVED** [review]
