### PR TITLE
Fix/333 fix visibility logic in search screen

### LINKED ISSUE #333: Fix visibility logic of search title and list of search result in search screen
- search title should appear if there is a history result or network result
- show history result if present
- show network result if present
- search result icon should change based on keyboard shown or not
- for empty state from network show suggested keywords title only
- for empty state of both network and history don't show any thing
- fix icon back click shadow
- fix icon mic click shadow
- fix arrow and close icon shadow
- fix recent section delete animation
- fix shadow of clicked search item

Image

Image

Image

### PR DESCRIPTION
**Pull request by poula22**
- search title should appear if there is a history result or network result
- show history result if present
- show network result if present
- search result icon should change based on keyboard shown or not
- for empty state from network show suggested keywords title only
- for empty state of both network and history don't show any thing
- fix icon back click shadow
- fix icon mic click shadow
- fix arrow and close icon shadow
- fix recent section delete animation
- fix shadow of clicked search item
- refactor 

https://github.com/user-attachments/assets/1e59163b-f557-4194-99a6-863713f6e6d3

### CODE REVIEW

File: presentation/explore/src/main/java/com/giraffe/explore/components/ExploreHeader.kt [hunk 1]
```diff
@@ -53,39 +51,42 @@ fun ExploreHeader(
...
         ) {
             if (showBackButton) {
-                val isRtl = LocalLayoutDirection.current == LayoutDirection.Rtl
                 Image(
                     modifier = Modifier
-                        .padding(vertical = 10.dp)
-                        .padding(start = 10.dp)
-                        .size(20.dp)
+                        .padding(vertical = 6.dp, horizontal = 4.dp)
+                        .size(40.dp)
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/components/ExploreHeader.kt:64]: the previous size and padding were right. why did you change it??

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt [hunk 2]
```diff
@@ -91,13 +95,19 @@ private fun SearchContent(
                     interactions.onQueryChange(result)
                 }
                 interactions.onVoiceSearchFinished()
+            },
+            onSoundLevelChange = { level ->
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt]: why did you add this empty body?

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt [hunk 3]
```diff
@@ -115,7 +125,7 @@ private fun SearchContent(
 
     val focusRequester = remember { FocusRequester() }
     LaunchedEffect(Unit) {
-        focusRequester.requestFocus()
+        if (state.query.isBlank()) focusRequester.requestFocus()
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt]: why did you add this condition? we already need this field to be focused once i enter the screen, whether its content is empty or not

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt [hunk 4]
```diff
@@ -176,51 +186,53 @@ private fun LazyListScope.keywordsSection(
...
-        SectionTitle(
-            modifier = Modifier
-                .background(Theme.color.background.screen)
-                .padding(top = 24.dp, bottom = 8.dp, start = 16.dp, end = 16.dp),
-            title = if (isJustRecent) stringResource(R.string.history) else stringResource(R.string.search_suggestions),
-            clickableText = if (isJustRecent) stringResource(R.string.clear_all) else "",
-            onClickableText = onClearClick
-        )
-    }
+    val isRecentKeyWordsVisible = recentKeywords.isNotEmpty()
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt:214]: many variables make it harder to read

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt [hunk 5]
```diff
@@ -176,51 +186,53 @@ private fun LazyListScope.keywordsSection(
...
-                    keyWord
-                )
-            },
-        )
+    if (isRecentKeyWordsVisible) {
+        items(recentKeywords) { keyWord ->
+            SearchItem(
+                text = keyWord,
+                isRecent = true,
+                postfixIcon = if (isKeyboardVisible) painterResource(Theme.icons.outline.arrowRightUp)
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt:242]: what is the relation between Keyboard Visibility and the close icon to clear the item??

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchViewModel.kt [hunk 6]
```diff
@@ -33,6 +33,7 @@ class SearchViewModel(
 ) : BaseViewModel<SearchScreenState>(SearchScreenState()),
     SearchInteractionListener {
     init {
+        updateState { it.copy(isLoading = true) }
```
Comment (mohannadahmed00) [inline presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchViewModel.kt]: you can remove it and just initialize it in the SearchScreenState

**Review by mohannadahmed00 — DISMISSED** [review]

File: designsystem/src/main/java/com/giraffe/designsystem/composable/PosterListSection.kt [hunk 7]
```diff
@@ -21,12 +28,18 @@ fun PosterListSection(
...
     paddingHorizontal: Int = 16,
     onClickEndText: () -> Unit = {},
     onClickPoster: (poster: Poster) -> Unit = {}
 ) {
-    AnimatedVisibility(posters.isNotEmpty()) {
+    AnimatedVisibility(
+        visible = posters.isNotEmpty(),
+        enter = fadeIn(fadeAnimationSpec),
+        exit = fadeOut(fadeAnimationSpec) + slideOutHorizontally(slideAnimationSpec) { -it }
+    ) {
```
Comment (skaik-mo) [inline designsystem/src/main/java/com/giraffe/designsystem/composable/PosterListSection.kt:46]: In RTL, swipe to remove still behaves like LTR. Adjust swipe direction based on layout.

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchViewModel.kt (hunk 6 above)
Comment (poula22) [reply presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchViewModel.kt]: I forget to remove it. I don't need loading here at all.❤️

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt (hunk 5 above)
Comment (poula22) [reply presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt:242]: check issue. icon changes based on keyboard visibility from close to arrow

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt (hunk 2 above)
Comment (poula22) [reply presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt]: this will be changed. all implementation of recognizer will be replaced with Google dialog

File: presentation/explore/src/main/java/com/giraffe/explore/components/ExploreHeader.kt (hunk 1 above)
Comment (poula22) [reply presentation/explore/src/main/java/com/giraffe/explore/components/ExploreHeader.kt:64]: same total padding

File: presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt (hunk 4 above)
Comment (poula22) [reply presentation/explore/src/main/java/com/giraffe/explore/screen/search/SearchScreen.kt:214]: I need them to make condition of search title readable

**Review by Mostafa-khaled21 — DISMISSED** [review]

**Review by skaik-mo — APPROVED** [review]

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]

**Review by Mostafa-khaled21 — APPROVED** [review]

**Review by doaaabdelnaser — APPROVED** [review]
