### PR TITLE
Fix/528 cast appbar wrong animation

### LINKED ISSUE #528: cast appbar wrong animation
- cast appbar animation not working if it has small content

### PR DESCRIPTION
**Pull request by poula22**
- topbar animation in CastDetailsScreen
- loading data animation with GallerySection, InfoSection, StaffInfoSection, PosterListSection and StarCastSection
- make MovieDetailsViewModel get data from usecases in parallel execution
- SeriesDetailsScreen content visibility 
- MovieDetailsScreen content visibility

### CODE REVIEW

File: presentation/details/src/main/java/com/giraffe/details/components/MainDetails.kt [hunk 1]
```diff
@@ -56,119 +56,125 @@ import com.giraffe.details.screens.castDetails.state.SocialMediaUi
...
-                        SocialMediaComponent(
-                            image = it.platform.getIcon(),
-                            name = stringResource(it.name),
-                            contentDescription = stringResource(it.contentDescription),
-                            onClick = { onLinkClick(it.url) }
-                        )
-                    }
+        }
+
+        if (socialMediaUiList.isNotEmpty() && animationProgress == 0f) {
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/details/components/MainDetails.kt]: Using `AnimatedVisibility` instead of a regular `if` statement to improve the UI transition experience.

File: presentation/details/src/main/java/com/giraffe/details/components/MainDetails.kt [hunk 2]
```diff
@@ -56,119 +56,125 @@ import com.giraffe.details.screens.castDetails.state.SocialMediaUi
...
-                    if (actorPlaceOfBirth.isNotBlank()) {
-                        IconTextBox(
-                            icon = painterResource(Theme.icons.outline.location),
-                            contentDescription = stringResource(R.string.location_icon),
-                            text = stringResource(R.string.place_of_birth) + singleSpace + actorPlaceOfBirth,
-                        )
-                    }
+                }
 
+                if (actorPlaceOfBirth.isNotBlank() && animationProgress == 0f) {
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/details/components/MainDetails.kt]: Using `AnimatedVisibility` instead of a regular `if` statement to improve the UI transition experience.

File: presentation/details/src/main/java/com/giraffe/details/components/MainDetails.kt [hunk 3]
```diff
@@ -56,119 +56,125 @@ import com.giraffe.details.screens.castDetails.state.SocialMediaUi
...
+            }
+
+            Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
+                Text(
+                    style = Theme.textStyle.title.md,
+                    color = Theme.color.shade.primary,
+                    text = actorName
+                )
+
+                if (actorBirthday.isNotBlank() && animationProgress == 0f) {
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/details/components/MainDetails.kt]: Using `AnimatedVisibility` instead of a regular `if` statement to improve the UI transition experience.

**Review by skaik-mo — CHANGES_REQUESTED** [review]
- The placeholder in both the movie card and cast items doesn't match the design specs. Align it with the provided design for consistency.

image

- Design
image

**Comment by skaik-mo** [comment]
and also in the Cast Details screen does not match the design.

image

File: presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsScreen.kt [hunk 4]
```diff
@@ -85,40 +77,43 @@ fun CastDetailsScreen(
...
     }
-    if (state.isLoading) {
-        LoadingView()
-    } else {
-        Box(
-            modifier = modifier
-                .fillMaxSize()
-                .background(Theme.color.background.screen)
-                .wrapContentSize()
+//    if (state.isLoading) {
```
Comment (HendSayed25) [inline presentation/details/src/main/java/com/giraffe/details/screens/castDetails/CastDetailsScreen.kt]: remove this comment

**Review by skaik-mo — APPROVED** [review]

**Review by HendSayed25 — APPROVED** [review]
