### PR TITLE
Fix/home internet exception

### LINKED ISSUE #394: App crash when no internet connection.

### LINKED ISSUE #407: fix Carousel exception
- when pass empty list make the app crash

### PR DESCRIPTION
**Pull request by mohamedebrahem13**
- home internet exception 
- home list view model exception  
- home view model exception 
- refactor the view models 
- after changes in base like add error method and Coroutine Exception Handler exception

### CODE REVIEW

File: presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt [hunk 1]
```diff
@@ -39,10 +40,13 @@ fun Carousel(
     movieCards: List<PopularMediaUiModel>,
     onClickItem: (Int, MediaType) -> Unit
 ) {
+    if (movieCards.isEmpty()) return
```
Comment (HendSayed25) [inline presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt:43]: why add this condtion?

File: presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt [hunk 2]
```diff
@@ -39,10 +40,13 @@ fun Carousel(
...
     val pagerState = rememberPagerState(2) { movieCards.size }
     val currentMovieCard = movieCards[pagerState.currentPage]
-    val screenWidthDp = LocalConfiguration.current.screenWidthDp.dp
-    val width = screenWidthDp - 48.dp
+    val density = LocalDensity.current
+
+    val screenWidth = with(density) { LocalWindowInfo.current.containerSize.width.toDp() }
```
Comment (HendSayed25) [inline presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt:48]: can you explain to me why calculate screen Width by this method rather than before?

Comment (mohamedebrahem13) [reply presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt:48]: this is the new way it was suggestion by ide, and this remove the warning @HendSayed25

File: presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt (hunk 1 above)
Comment (mohamedebrahem13) [reply presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt:43]: the default value is empty list and this cous exception when Carousel try accesses items

File: presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt (hunk 2 above)
Comment (HendSayed25) [reply presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt:48]: the warning of what?

File: presentation/home/src/main/java/com/giraffe/home/screen/home/HomeScreen.kt [hunk 3]
```diff
@@ -111,153 +115,179 @@ fun HomeContent(
...
-        modifier = Modifier
-            .fillMaxSize()
-            .background(Theme.color.background.screen)
-            .statusBarsPadding()
-    ) {
-        stickyHeader {
-            TopAppBar(
-                userName = state.userName
+    if (state.isGenricError && state.isNetworkError) {
+        Column(
```
Comment (Mohamed-Ashraf-2210) [inline presentation/home/src/main/java/com/giraffe/home/screen/home/HomeScreen.kt:119]: can you put this column in composable package in design system

**Review by Mohamed-Ashraf-2210 — CHANGES_REQUESTED** [review]

File: presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt (hunk 2 above)
Comment (mohamedebrahem13) [reply presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt:48]: ide warning tells me the code is deprecated

**Review by HendSayed25 — DISMISSED** [review]

**Review by Mohamed-Ashraf-2210 — DISMISSED** [review]

File: presentation/home/src/main/java/com/giraffe/home/base/BaseViewModel.kt [hunk 4]
```diff
@@ -32,5 +32,21 @@ abstract class BaseViewModel<S, E>(initialState: S): ViewModel() {
             _effect.send(effect)
         }
     }
+    protected fun <T> safeExecute(
+        coroutineScope: CoroutineScope = viewModelScope,
+        dispatcher: CoroutineDispatcher = Dispatchers.IO,
+        exceptionHandler: CoroutineExceptionHandler = handler(),
+        block: suspend CoroutineScope.() -> T
```
Comment (dev-bilal-azzam) [inline presentation/home/src/main/java/com/giraffe/home/base/BaseViewModel.kt:39]: it is better to send the success handling and error hndling separated from the call itself
        block: suspend CoroutineScope.() -> T,
        onSuccess: (T) -> Unit,
        onError: (Throwable) -> Unit

File: presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt [hunk 5]
```diff
@@ -47,95 +44,103 @@ class HomeViewModel(
...
-                    )
-                }
-
-            } catch (e: MediaException) {
-                val errorResId = mapExceptionToStringRes(e)
-                updateState { it.copy(isLoading = false, isError = true) }
-                sendEffect(HomeEffect.ShowError(errorResId))
+        updateState { it.copy(isLoading = true, isGenricError = false) }
+
+        safeExecute {
```
Comment (dev-bilal-azzam) [inline presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt]: I'd prefer this function to be smaller,
those requests doesn't have to wait for each other

Comment (mohamedebrahem13) [reply presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt]: they must wait each other

Comment (dev-bilal-azzam) [reply presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt]: why??

Comment (mohamedebrahem13) [reply presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt]: they depend on each other,  simple!

**Review by HendSayed25 — APPROVED** [review]

**Review by Mostafa-khaled21 — APPROVED** [review]

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]

**Review by mohannadahmed00 — APPROVED** [review]
