### PR TITLE
Fix/add single line to search field and make max characters 100

### LINKED ISSUE #242: Make Search Bar Single Line – Prevent New Line Input
### The search bar currently allows users to enter new lines (line breaks), which causes a poor user experience. It should be restricted to a single line input only.

https://github.com/user-attachments/assets/8a60f6b0-18fe-47d8-bd10-fcf96ac716ba

### PR DESCRIPTION
**Pull request by poula22**
add single line to search field and make max characters 100

https://github.com/user-attachments/assets/263c5ac6-f666-49cb-a0c0-7305e54b5aec

### CODE REVIEW

File: designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt [hunk 1]
```diff
@@ -133,11 +135,13 @@ fun DefaultTextField(
                 modifier = Modifier
                     .weight(1f)
                     .fillMaxHeight()
-                    .focusRequester(focusRequester),
+                    .focusRequester(focusRequester)
+                    .semantics { },
```
Comment (AhmedMohamed056) [inline designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt]: What's this? And why did you use it?

Comment (poula22) [reply designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt]: I forget to remove it.

By the way this should be use for accessibility and auto fill fields when we have form like login form

Comment (poula22) [reply designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt]: Do you know what is focus requster modifier for ?

**Review by HendSayed25 — DISMISSED** [review]
👏

**Review by skaik-mo — CHANGES_REQUESTED** [review]
Good work! However, when I paste a sentence with a line break, like:
```
batman  
spiderman
```
it doesn’t return any results. I suggest handling the input to extract words split by line breaks and include them in the query. This would improve search flexibility and user experience.

https://github.com/user-attachments/assets/940dc651-b8a4-410b-bad6-01eece772165

**Review by AhmedMohamed056 — DISMISSED** [review]

**Review by doaaabdelnaser — DISMISSED** [review]

**Review by skaik-mo — APPROVED** [review]

**Review by AhmedMohamed056 — APPROVED** [review]

**Review by doaaabdelnaser — APPROVED** [review]

File: designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt [hunk 2]
```diff
@@ -140,7 +141,13 @@ fun DefaultTextField(
                 value = value,
                 maxLines = maxLines,
                 singleLine = singleLine,
-                onValueChange = { if (it.length <= maxCharacters) onValueChange(it) },
+                onValueChange = {
+                    Log.i("maxCharacters", it.length.toString())
```
Comment (HendSayed25) [inline designsystem/src/main/java/com/giraffe/designsystem/composable/DefaultTextField.kt:145]: remove this log if all work good :)

**Review by HendSayed25 — APPROVED** [review]
