### PR TITLE
fix loading in cast credit

### LINKED ISSUE #817: Long Loading inCast Credits Show More Screen

### PR DESCRIPTION
**Pull request by mohamedebrahem13**
- fix loading in cast credit

### CODE REVIEW

**Review by Mohamed-Ashraf-2210 — DISMISSED** [review]

**Review by poula22 — APPROVED** [review]

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt [hunk 1]
```diff
@@ -50,13 +50,16 @@ class CastCreditViewModel @Inject constructor(
             onSuccess = ::updateCastCreditPosters,
             onError = ::loadCastCreditError
         ) {
+            val allSeriesGenres = getSeriesGenresByIds(emptyList())
+            val allMoviesGenres = getMoviesGenresByIds(emptyList())
```
Comment (poula22) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt]: This can cause race condition. it should be hold in stateFlow

**Review by poula22 — CHANGES_REQUESTED** [review]

**Review by poula22 — DISMISSED** [review]

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt [hunk 2]
```diff
@@ -33,8 +33,22 @@ class CastCreditViewModel @Inject constructor(
 
     init {
         observeContentPreference()
-        state.value.castId?.let {
-            loadCastCredit(it)
+
+        safeExecute(
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt]: Separating the safeExecute logic into its own function for better readability. Also, it would be clearer if the onSuccess block is extracted into a separate function.

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt [hunk 3]
```diff
@@ -33,8 +33,22 @@ class CastCreditViewModel @Inject constructor(
...
+                        allSeriesGenres = series,
+                        allMovieGenres = movies
+                    )
+                }
+                state.value.castId?.let { loadCastCredit(it) }
+            },
+            onError = ::loadCastCreditError
+        ) {
+            val series = getSeriesGenresByIds(emptyList())
+            val movies = getMoviesGenresByIds(emptyList())
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt]: Use `safeExecute` for each use case to ensure consistency and safer execution handling.

Comment (skaik-mo) [reply presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt]: Also, using `ObserveSeriesGenresUseCase` and `ObserveMoviesGenresUseCase` instead of `GetSeriesGenresByIdsUseCase` and `GetMoviesGenresByIdsUseCase`

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt [hunk 4]
```diff
@@ -54,19 +68,22 @@ class CastCreditViewModel @Inject constructor(
             onError = ::loadCastCreditError
         ) {
             val seriesPosters = castCredits.series.map {
-                val genres = getSeriesGenresByIds(it.genreIDs).map { genre -> genre.title }
+                val genres = it.genreIDs.mapNotNull { id ->
+                    state.value.allSeriesGenres.find { g -> g.id == id }?.title
+                }
                 it.toUi().toPoster().copy(genres = genres.joinToString(", "))
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt]: `joinToString(", ")` is already handled inside toPoster, so it can be removed here to avoid duplication.

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt [hunk 5]
```diff
@@ -54,19 +68,22 @@ class CastCreditViewModel @Inject constructor(
...
             }
 
             val moviesPosters = castCredits.movies.map {
-                val genres = getMoviesGenresByIds(it.genresID).map { genre -> genre.title }
+                val genres = it.genresID.mapNotNull { id ->
+                    state.value.allMovieGenres.find { g -> g.id == id }?.title
+                }
                 it.toUi().toPoster().copy(genres = genres.joinToString(", "))
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt]: also here
> joinToString(", ") is already handled inside toPoster, so it can be removed here to avoid duplication.

**Review by skaik-mo — CHANGES_REQUESTED** [review]
After fixing the bugs, the genres should appear as expected. Ensure they are displayed correctly.

https://github.com/user-attachments/assets/884b69dc-8986-4ab1-943f-f79433f0a0b1

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt [hunk 6]
```diff
@@ -54,19 +80,22 @@ class CastCreditViewModel @Inject constructor(
             onError = ::loadCastCreditError
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditViewModel.kt]: Remove `safeExecute` here, it’s not needed in this context.

**Review by poula22 — DISMISSED** [review]

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditInteractionListener.kt [hunk 7]
```diff
@@ -7,6 +7,4 @@ interface CastCreditInteractionListener {
     fun onPosterClick(mediaId: Int, mediaType: String)
 
     fun changeView(isGrid: Boolean)
-
-    fun onRetryClick()
```
Comment (HendSayed25) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditInteractionListener.kt]: Why remove this function???

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditScreen.kt [hunk 8]
```diff
@@ -50,7 +50,6 @@ private fun CastCreditContent(
     BaseScreen(
         isLoading = state.isLoading,
         isNoInternet = state.isNoInternet,
-        onRetryClick = interaction::onRetryClick,
```
Comment (HendSayed25) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditScreen.kt]: This used  to handle the case when disconnect the internet and return again , why remove it ?

Comment (mohamedebrahem13) [reply presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditScreen.kt]: Ask @skaik-mo

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditInteractionListener.kt (hunk 7 above)
Comment (mohamedebrahem13) [reply presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditInteractionListener.kt]: @skaik-mo Ask

Comment (skaik-mo) [reply presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditInteractionListener.kt]: We don’t need `onRetryClick`. It’s meant for re-requesting `loadCastCredit` when a cast ID is not found, but since we always have a valid cast ID, this case will never occur.

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditScreen.kt (hunk 8 above)
Comment (skaik-mo) [reply presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditScreen.kt]: Now I understand why we need `onRetryClick`. It makes sense to keep it for handling cases when there is no internet connection.

**Review by HendSayed25 — APPROVED** [review]

**Review by Mostafa-khaled21 — APPROVED** [review]

**Review by skaik-mo — APPROVED** [review]
