### PR TITLE
Fix user name and multiple clicks on card

### LINKED ISSUE #387: Home Screen: username instead of Ashraf.
- when join by user name appear it's name in home screen

### PR DESCRIPTION
**Pull request by Ashraf-El-Fallah**
-Get user name when User log in and appear it in home screen
- fix navigation many time when user click multiple times on card

note: i tried create extension function to modifier but i faced a lot of bad behaviour so i think rap the content in  multipleEventsCutter will work fine

https://github.com/user-attachments/assets/4bbd11d6-3a2e-4b13-a1f8-275ec14130d9

https://github.com/user-attachments/assets/b20e1565-e620-4926-a0ec-cf9e30cb200f

### CODE REVIEW

File: presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt [hunk 1]
```diff
@@ -57,6 +60,20 @@ class HomeViewModel @Inject constructor(
         getRecentlyReleased()
         getTopRatedSeries()
         getUpcomingMovies()
+        getUserName()
+    }
+
+    private fun getUserName() {
```
Comment (devfalah) [inline presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt:65]: I think @HendSayed25 fixed this issue

File: presentation/home/src/main/java/com/giraffe/home/utils/DebounceClick.kt [hunk 2]
```diff
@@ -0,0 +1,44 @@
...
+import kotlinx.coroutines.flow.MutableSharedFlow
+import kotlinx.coroutines.flow.debounce
+
+interface MultipleEventsCutterManager {
+    fun processEvent(event: () -> Unit)
+}
+
+@OptIn(FlowPreview::class)
+@Composable
+fun <T> multipleEventsCutter(
```
Comment (devfalah) [inline presentation/home/src/main/java/com/giraffe/home/utils/DebounceClick.kt]: No need for this please check this answer: [https://stackoverflow.com/a/76386604](https://stackoverflow.com/a/76386604)

Image

File: presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt (hunk 1 above)
Comment (Ashraf-El-Fallah) [reply presentation/home/src/main/java/com/giraffe/home/screen/home/HomeViewModel.kt:65]: I connected with her and will solve this conflict @devfalah

File: presentation/home/src/main/java/com/giraffe/home/utils/DebounceClick.kt (hunk 2 above)
Comment (Ashraf-El-Fallah) [reply presentation/home/src/main/java/com/giraffe/home/utils/DebounceClick.kt]: Done .. thank you Falah for this great and simple solution @devfalah

**Review by skaik-mo — CHANGES_REQUESTED** [review]
- The issue with the back button still persists.

https://github.com/user-attachments/assets/0e11960c-5ebf-430d-b157-0f5668bc301a

- The name should be displayed first. If the user doesn't have a name, fallback to displaying the username.

image

**Comment by Ashraf-El-Fallah** [comment]
I fix back button .. user name will fix from porfile team @skaik-mo 

https://github.com/user-attachments/assets/0eb690e0-11c1-43c2-ad9b-c0ae3bf94c26

**Review by mohannadahmed00 — APPROVED** [review]

**Review by devfalah — APPROVED** [review]

**Review by skaik-mo — APPROVED** [review]
