### PR TITLE
Apply min height constraint to season card poster

### LINKED ISSUE #392: Incorrect Card Layout When Season Info is Limited
The current implementation does not correctly reflect the intended design when a season comes from the API with only a title and poster (i.e., no overview, rating, episode count, or release year). In such cases, the card should still maintain the designed layout for minimal data: a centered image and title only, without placeholders for missing data.

- Current Implementation (Broken Layout):

Image

- Intended Layout for Minimal Info (Design Example):

Image

Expected Behavior:
When a season lacks description and metadata (rating, episode count, year), the UI should:
- Display only the poster and title.
- Hide empty placeholders.

### PR DESCRIPTION
**Pull request by mohannadahmed00**
The season card poster will now have a minimum height of 71.dp. This ensures that even if the image loaded is smaller, the layout maintains a consistent minimum height for the poster area.

WhatsApp Image 2025-07-29 at 16 50 30_95c5be07

### CODE REVIEW

**Review by AhmedMohamed056 — APPROVED** [review]

**Review by skaik-mo — APPROVED** [review]

File: presentation/details/src/main/java/com/giraffe/details/components/SeasonCard.kt [hunk 1]
```diff
@@ -71,12 +72,12 @@ fun SeasonCard(
                     .fillMaxWidth()
                     .height(intrinsicSize = IntrinsicSize.Min),
                 horizontalArrangement = Arrangement.spacedBy(12.dp),
-                verticalAlignment = Alignment.CenterVertically
             ) {
```
Comment (Mohamed-Ashraf-2210) [inline presentation/details/src/main/java/com/giraffe/details/components/SeasonCard.kt:75]: make this column center horizontal

```
Column {
                    Text(
                        modifier = Modifier.padding(bottom = 4.dp),
                        text = title,
                        style = Theme.textStyle.body.md.medium,
                        color = Theme.color.shade.primary
                    )
                    AnimatedVisibility(overview.isNotBlank()) {
                        Text(
                            text = overview,
                            style = Theme.textStyle.body.sm.regular,
                            color = Theme.color.shade.secondary,
                            maxLines = 4,
                            minLines = 3,
                            overflow = TextOverflow.Ellipsis
                        )
                    }
}
```

when overview is empty, title still in top column

**Review by Mohamed-Ashraf-2210 — CHANGES_REQUESTED** [review]

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]

**Review by poula22 — APPROVED** [review]
