### PR TITLE
Fix date and duration movie details

### LINKED ISSUE #316: Fix Incorrect release date Format in MainMovieOrSeriesDetailsAnimatedContent Component
The release date is not displayed in the correct format. Ensure it follows the expected date format depending on desgin.

Design

Image

Our App

Image

### PR DESCRIPTION
**Pull request by Mohamed-Ashraf-2210**
add duration and format date in details screen

Screenshot_20250727_122922_CineVerse App
Screenshot_20250727_122937_CineVerse App

### CODE REVIEW

File: repository/media/src/main/java/com/giraffe/media/movie/MoviesRepositoryImpl.kt [hunk 1]
```diff
@@ -99,11 +99,7 @@ class MoviesRepositoryImpl(
     override suspend fun clearRecentlyMovies() = SafeCall { local.clearRecentlyMovies() }
 
     override suspend fun getMovieDetails(movieId: Int) = SafeCall {
-//        Log.d("TAG", "getMovieDetails: ${cache.getMovieById(movieId)?.toEntity()}")
-//        Log.d("TAG", "getMovieDetails: ${remote.getMovieById(movieId)}")
-        local.getMovieById(movieId)?.toEntity() ?: remote.getMovieById(movieId)
```
Comment (HendSayed25) [inline repository/media/src/main/java/com/giraffe/media/movie/MoviesRepositoryImpl.kt:104]: why delete line of checking movie details from local first ?

Comment (Mohamed-Ashraf-2210) [reply repository/media/src/main/java/com/giraffe/media/movie/MoviesRepositoryImpl.kt:104]: we don't need to insert details screen in database

**Review by dev-bilal-azzam — DISMISSED** [review]

**Review by HendSayed25 — DISMISSED** [review]

**Review by Mostafa-khaled21 — DISMISSED** [review]

File: presentation/details/src/main/java/com/giraffe/details/utils/ConvertFormatted.kt [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+}
+
+fun String.toFormattedDate(): String {
+    if (this.isBlank()) return this
+    val inputFormat = SimpleDateFormat("yyyy-M-dd", Locale.ENGLISH)
+    val date = inputFormat.parse(this) ?: return this
+
+    val monthSymbols = DateFormatSymbols(Locale.ENGLISH).apply {
+        months = arrayOf(
+            "Jan", "Feb", "Mar", "Apr",
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/details/utils/ConvertFormatted.kt]: Use the format `yyyy, MMM d` for consistency. Remove the use of `monthSymbols` and `apply` from `outputFormat`, and ensure the output respects the app’s current language settings for localization.

File: repository/media/src/main/java/com/giraffe/media/movie/MoviesRepositoryImpl.kt (hunk 1 above)
Comment (skaik-mo) [reply repository/media/src/main/java/com/giraffe/media/movie/MoviesRepositoryImpl.kt:104]: Remove `getMovieById` from local if it's not being used to keep the code clean.

**Review by skaik-mo — DISMISSED** [review]

File: presentation/details/src/main/java/com/giraffe/details/utils/ConvertFormatted.kt [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+fun Int.toFormattedDuration(): String {
+    val hours = this / 60
+    val minutes = this % 60
+    return buildString {
+        if (hours > 0) append("${hours}h ")
+        if (minutes > 0 || hours == 0) append("${minutes}m")
+    }.trim()
+}
+
+fun String.toFormattedDate(): String {
```
Comment (mohannadahmed00) [inline presentation/details/src/main/java/com/giraffe/details/utils/ConvertFormatted.kt:15]: I think it is not a goo idea to be Sting extention because not all strings will be compatible with it.

**Review by mohannadahmed00 — DISMISSED** [review]

**Review by mohamedebrahem13 — APPROVED** [review]

**Review by Ashraf-El-Fallah — APPROVED** [review]

**Review by mohannadahmed00 — APPROVED** [review]

**Review by HendSayed25 — APPROVED** [review]
