### PR TITLE
Fix/home screen issues

### LINKED ISSUE #733: Home screen

### PR DESCRIPTION
**Pull request by Mohamed-Ashraf-2210**
#742 
#734
#735 
#737

### CODE REVIEW

File: presentation/home/src/main/java/com/giraffe/presentation/home/utils/formattedDuration.kt [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package com.giraffe.presentation.home.utils
+
+fun Int?.formatDuration(): String {
```
Comment (mohamedebrahem13) [inline presentation/home/src/main/java/com/giraffe/presentation/home/utils/formattedDuration.kt]: fun Int?.formatDuration(): String =
    this?.takeIf { it > 0 }?.let { totalMinutes ->
        val hours = totalMinutes / 60
        val minutes = totalMinutes % 60
        buildString {
            if (hours > 0) append("${hours}h ")
            if (minutes > 0) append("${minutes}m")
        }.trim()
    } ?: ""

**Review by mohamedebrahem13 — DISMISSED** [review]

File: presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/CategoryMediaViewModel.kt [hunk 2]
```diff
@@ -21,15 +21,21 @@ import kotlinx.coroutines.flow.stateIn
...
     stateSavedStateHandle: SavedStateHandle
-) : BaseViewModel<ShowMoreScreenState, ShowMoreEffect>(ShowMoreScreenState()),
-    ShowMoreInteractionListener {
+) : BaseViewModel<CategoryMediaScreenState, CategoryMediaEffect>(CategoryMediaScreenState()),
+    CategoryMediaInteractionListener {
 
     private val sectionType = stateSavedStateHandle.toRoute<ShowMoreRoute>().sectionType
 
     init {
+        updateState {
```
Comment (Mostafa-khaled21) [inline presentation/home/src/main/java/com/giraffe/presentation/home/screen/show_more/CategoryMediaViewModel.kt:37]: I think it is better to have it inside loadByStrategy ?

**Review by Mostafa-khaled21 — DISMISSED** [review]

**Review by mohamedebrahem13 — APPROVED** [review]

**Review by Mostafa-khaled21 — APPROVED** [review]
