### PR TITLE
Fix/335 error message in login

### LINKED ISSUE #335: Redundant error message shown for invalid login credentials
When a user enters an incorrect username or password, the application displays the identical error message "Invalid Username or Password" beneath both the username field and the password field simultaneously. 

Image

### PR DESCRIPTION
**Pull request by poula22**
-  handle search result issue
- add exception for non characters and numbers username
- add error message for invalid username and password
- change lightThemeColor of disable button
- make button disable at start of writing
- make PrimaryButton and SecondaryButton animate content which is text or progress indicator

https://github.com/user-attachments/assets/73744066-0283-458f-acd9-f1906e41fe15

### CODE REVIEW

**Review by HendSayed25 — DISMISSED** [review]

File: presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginViewModel.kt [hunk 1]
```diff
@@ -48,50 +49,65 @@ class LoginViewModel(
...
+                    screenErrorMessage = exceptionMessage,
+                    isLoadingLogin = false,
+                    usernameErrorMessage = null,
+                    passwordErrorMessage = null
                 )
             }
         }
 
-        updateState { it.copy(isLoadingLogin = false) }
+        updateState { it.copy() }
```
Comment (mohannadahmed00) [inline presentation/authentication/src/main/java/com/giraffe/authentication/screen/LoginViewModel.kt]:
```suggestion
        
```

**Review by mohannadahmed00 — DISMISSED** [review]

**Review by HendSayed25 — APPROVED** [review]

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]

**Review by AhmedMohamed056 — APPROVED** [review]

**Review by skaik-mo — APPROVED** [review]
