### PR TITLE
Fix/home screen crash when no internet

### LINKED ISSUE #489: Home Screen Crash When No Internet Connection

### PR DESCRIPTION
**Pull request by dev-bilal-azzam**
Fix the crash in home screen when no internet

### CODE REVIEW

File: presentation/home/src/main/java/com/giraffe/home/base/BaseViewModel.kt [hunk 1]
```diff
@@ -67,8 +68,22 @@ abstract class BaseViewModel<S, E>(initialState: S) : ViewModel() {
...
+        return coroutineScope.launch(dispatcher + handler(onError)) {
+            val data = block()
+            onSuccess(data)
+        }
+    }
+
     private fun handler(onError: (Int) -> Unit = {}): CoroutineExceptionHandler {
         return CoroutineExceptionHandler { _, throwable ->
+            Log.d("TAG", "handler: $throwable")
             onError(mapExceptionToStringRes(throwable))
```
Comment (AhmedMohamed056) [inline presentation/home/src/main/java/com/giraffe/home/base/BaseViewModel.kt:87]: delete log

**Review by AhmedMohamed056 — APPROVED** [review]

**Review by HendSayed25 — APPROVED** [review]
