### PR TITLE
Fix join as guest issues

### LINKED ISSUE #732: Login as guest issue
- When user join as guest not appear login screen again untill go to the profile for log in with his account or register

### PR DESCRIPTION
**Pull request by HendSayed25**
# What's Update ?

- Add guest session support and improve login handling
- Implement guest login and session creation use case
- Handle guest session exceptions and loading state
- Update UI to reflect guest status (title visibility, profile info, etc.)
- Add new string resource for session ID error

https://github.com/user-attachments/assets/e077f1f0-cd32-4d5c-b1aa-a5f9136fff12

### CODE REVIEW

**Review by poula22 — DISMISSED** [review]

File: datasource/local/user/src/main/java/com/giraffe/user/datastore/AuthenticationDatastore.kt [hunk 1]
```diff
@@ -30,8 +31,27 @@ class AuthenticationDatastore @Inject constructor(
         }
     }
 
+    suspend fun setTheUserAsGuest() {
```
Comment (mohamedebrahem13) [inline datasource/local/user/src/main/java/com/giraffe/user/datastore/AuthenticationDatastore.kt]: Can you remove "  the " here for the naming

File: datasource/local/user/src/main/java/com/giraffe/user/AuthenticationLocalDataSourceImpl.kt [hunk 2]
```diff
@@ -6,18 +6,28 @@ import com.giraffe.user.util.safeCall
...
+    private val authenticationDatastore: AuthenticationDatastore,
 ) : AuthenticationLocalDataSource {
     override suspend fun saveSessionId(sessionId: String) =
         safeCall { authenticationDatastore.saveSessionId(sessionId) }
 
     override suspend fun getSessionId(): String? =
         safeCall { authenticationDatastore.getSessionId() }
 
+    override suspend fun isLoggedInByAccount(): Boolean =
+        safeCall { authenticationDatastore.getSessionId() != null && !authenticationDatastore.isUserGuest() }
```
Comment (mohamedebrahem13) [inline datasource/local/user/src/main/java/com/giraffe/user/AuthenticationLocalDataSourceImpl.kt:18]: Does user gust create session id? I think no ,then you don't need the and check

File: datasource/remote/user/src/main/java/com/giraffe/user/retrofit/UserApiService.kt [hunk 3]
```diff
@@ -15,22 +15,29 @@ import retrofit2.http.Query
...
+    suspend fun getUser(@Query(SESSION_ID) sessionId: String): Response<UserDto>
 
-    @HTTP(method = "DELETE", path = "authentication/session", hasBody = true)
+    @HTTP(method = DELETE, path = DELETE_SESSION_URL, hasBody = true)
     suspend fun deleteSession(@Body requestBody: DeleteSessionRequest): Response<Unit>
 
+
     companion object {
-        private const val AUTHENTICATION = "authentication"
+        private const val CREATE_REQUEST_TOKEN = "authentication/token/new"
```
Comment (Mostafa-khaled21) [inline datasource/remote/user/src/main/java/com/giraffe/user/retrofit/UserApiService.kt]: Remove the companion object and use each string in its place. The last code review was Falah, who talked to us about this part.

File: datasource/local/user/src/main/java/com/giraffe/user/AuthenticationLocalDataSourceImpl.kt (hunk 2 above)
Comment (poula22) [reply datasource/local/user/src/main/java/com/giraffe/user/AuthenticationLocalDataSourceImpl.kt:18]: Guest can have session Id, but we didn't have time to use it now

**Review by mohamedebrahem13 — APPROVED** [review]

**Review by Mostafa-khaled21 — APPROVED** [review]
