### PR TITLE
322 app crashes when clicking poster on recommended screen

### LINKED ISSUE #322: App Crashes When Clicking Poster on Recommended Screen
Clicking on a poster in the Recommended screen causes the app to crash.

Investigate the navigation or data handling related to poster clicks to identify and fix the root cause.

https://github.com/user-attachments/assets/0bb1154c-e55b-45fc-901b-59a10f91115a

### PR DESCRIPTION
**Pull request by doaaabdelnaser**

### CODE REVIEW

File: presentation/details/src/main/java/com/giraffe/details/screens/recommended/movie/RecomendedContent.kt [hunk 1]
```diff
@@ -92,7 +93,10 @@ private fun CardsSection(
             lazyPagingItems = lazyPagingItems,
             isListSelected = !isGridSelected,
             contentPadding = PaddingValues(vertical = 5.dp),
-            onItemClick = onItemClick
+            onItemClick = { movieId ->
+                movieId?.let {
+                    onItemClick(it)
+                } ?: Log.e("RecommendedMovies", "Movie ID is null.")}
```
Comment (Mohamed-Ashraf-2210) [inline presentation/details/src/main/java/com/giraffe/details/screens/recommended/movie/RecomendedContent.kt:99]: remove log

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]

**Comment by doaaabdelnaser** [comment]
Uploading Screen_recording_20250729_150537.mp4…

**Comment by doaaabdelnaser** [comment]
Uploading Screen_recording_20250729_150537.mp4…

**Review by dev-bilal-azzam — APPROVED** [review]

**Review by HendSayed25 — APPROVED** [review]

**Review by Ashraf-El-Fallah — APPROVED** [review]
