### PR TITLE
Fix nullable data in Person Crediate

### LINKED ISSUE #448: Best of: title is empty and date is null
Image
Image

### PR DESCRIPTION
**Pull request by HendSayed25**
- Fix nullable date and title

# nullable data
Image

# solved
Image

### CODE REVIEW

File: presentation/details/src/main/java/com/giraffe/details/components/PosterHorizontal.kt [hunk 1]
```diff
@@ -44,107 +43,111 @@ fun PosterHorizontal(
...
-        modifier = modifier
-            .height(IntrinsicSize.Min)
-            .clip(RoundedCornerShape(Theme.radius.lg))
-            .background(Theme.color.background.card)
-            .clickable(onClick = onClick),
-        verticalAlignment = Alignment.CenterVertically,
-        horizontalArrangement = Arrangement.spacedBy(12.dp)
-    ) {
-        with(sharedTransitionScope) {
+    if (poster.name.isNotBlank()) {
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/details/components/PosterHorizontal.kt]: Using AnimatedVisibility here

File: presentation/details/src/main/java/com/giraffe/details/components/PosterHorizontal.kt [hunk 2]
```diff
@@ -44,107 +43,111 @@ fun PosterHorizontal(
...
-            ) {
-                Icon(
-                    painter = painterResource(Theme.icons.dueTone.image),
-                    contentDescription = stringResource(R.string.loading_image),
+                SafeIslamicImage(
+                    imageUrl = poster.imageUri,
+                    contentDescription = poster.name,
                     modifier = Modifier
-                        .fillMaxHeight()
+                        .height(88.dp)
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/details/components/PosterHorizontal.kt:64]: Replace `height(88.dp)` to `heightIn(min = 88.dp )`

File: presentation/details/src/main/java/com/giraffe/details/components/PosterHorizontal.kt [hunk 3]
```diff
@@ -44,107 +43,111 @@ fun PosterHorizontal(
...
-                    )
-                }
 
-                if (!poster.date.isNullOrBlank()) {
-                    IconWithText(
-                        modifier = Modifier.padding(top = 8.dp),
-                        icon = painterResource(Theme.icons.dueTone.calendar),
-                        text = poster.date.toString()
-                    )
+                    if (!poster.date.isNullOrBlank()) {
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/details/components/PosterHorizontal.kt]: also here, using AnimatedVisibility

File: presentation/details/src/main/java/com/giraffe/details/components/PosterHorizontal.kt [hunk 4]
```diff
@@ -44,107 +43,111 @@ fun PosterHorizontal(
...
 
-                    if (poster.rating != 0f) {
-                        Rating(
-                            value = poster.rating,
-                            modifier = Modifier
-                                .sharedElement(
-                                    sharedContentState = rememberSharedContentState(key = "rate - ${poster.id}"),
-                                    animatedVisibilityScope = animatedVisibilityScope
-                                )
+                    if (!poster.time.isNullOrBlank()) {
```
Comment (skaik-mo) [inline presentation/details/src/main/java/com/giraffe/details/components/PosterHorizontal.kt]: also here, using AnimatedVisibility

**Review by Ashraf-El-Fallah — APPROVED** [review]

**Review by poula22 — APPROVED** [review]

**Review by skaik-mo — APPROVED** [review]

**Review by mohannadahmed00 — APPROVED** [review]
