### PR TITLE
Fix authentication bugs phase 1

### LINKED ISSUE #484: Sign UP Bugs
# Should Handle :
- webview should be restricted to register website only 
- when go to webView disappear the bottom sheet first then go to web view 
- add loading state instead of white screen when navigate to web view

### PR DESCRIPTION
**Pull request by HendSayed25**
# This PR solved the following :

1-  Sign up Bugs :
- Webview should be restricted to register website only
- When go to webView disappear the bottom sheet first then go to web view 
- Add loading state instead of white screen when navigate to web view 
- Edit the padding of create account button

2-  Enhance structure of Authentication by 
- rename web view package and login 
- separate login content and screen to enhance the whole file

# Video summarize updates :
https://github.com/user-attachments/assets/3e891154-149f-425c-8138-bf13446f9332

### CODE REVIEW

File: presentation/authentication/src/main/java/com/giraffe/authentication/signup/AuthWebViewScreen.kt [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+import com.giraffe.designsystem.composable.Progress
+import com.giraffe.designsystem.theme.Theme
+import com.google.accompanist.web.AccompanistWebViewClient
+import com.google.accompanist.web.LoadingState
+import com.google.accompanist.web.WebView
+import com.google.accompanist.web.rememberWebViewState
+
+@Composable
+fun AuthWebViewScreen(onBack: () -> Unit) {
+    val signUpUrl = "https://www.themoviedb.org/signup"
```
Comment (Mohamed-Ashraf-2210) [inline presentation/authentication/src/main/java/com/giraffe/authentication/signup/AuthWebViewScreen.kt]: this part not clean 
can create file Constants.kt
and add this 
const val SIGN_UP_URL = "https://www.themoviedb.org/signup"

File: presentation/authentication/src/main/java/com/giraffe/authentication/signup/AuthWebViewScreen.kt [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+    var webViewState = rememberWebViewState(url = signUpUrl)
```
Comment (Mohamed-Ashraf-2210) [inline presentation/authentication/src/main/java/com/giraffe/authentication/signup/AuthWebViewScreen.kt]: add use here direct 
var webViewState = rememberWebViewState(url = SIGN_UP_URL)

File: presentation/authentication/src/main/java/com/giraffe/authentication/signup/AuthWebViewScreen.kt [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+    ) {
+
+        Column(modifier = Modifier.fillMaxSize()) {
+            AppBar(
+                title = stringResource(R.string.sign_up),
+                showBackButton = true,
+                onBackButtonClick = { onBack() },
+            )
+
+            // WebView Content
```
Comment (Mohamed-Ashraf-2210) [inline presentation/authentication/src/main/java/com/giraffe/authentication/signup/AuthWebViewScreen.kt]: Comment did not add anything

File: presentation/authentication/src/main/java/com/giraffe/authentication/login/screen/LoginScreen.kt [hunk 4]
```diff
@@ -0,0 +1,45 @@
...
+import com.giraffe.authentication.login.LoginViewModel
+
+@Composable
+fun LoginScreen(
+    modifier: Modifier = Modifier,
+    viewModel: LoginViewModel = hiltViewModel(),
+    navigateToHomeScreen: () -> Unit,
+    navigateToWebViewScreen: () -> Unit = {},
+    navigateToResetPasswordScreen: () -> Unit = {},
+    popBack: () -> Unit = {}
```
Comment (Mohamed-Ashraf-2210) [inline presentation/authentication/src/main/java/com/giraffe/authentication/login/screen/LoginScreen.kt]: change this name

File: presentation/authentication/src/main/java/com/giraffe/authentication/login/screen/LoginScreen.kt [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+import androidx.hilt.navigation.compose.hiltViewModel
+import com.giraffe.authentication.login.LoginEffect
+import com.giraffe.authentication.login.LoginViewModel
+
+@Composable
+fun LoginScreen(
+    modifier: Modifier = Modifier,
+    viewModel: LoginViewModel = hiltViewModel(),
+    navigateToHomeScreen: () -> Unit,
+    navigateToWebViewScreen: () -> Unit = {},
```
Comment (Mohamed-Ashraf-2210) [inline presentation/authentication/src/main/java/com/giraffe/authentication/login/screen/LoginScreen.kt]: why take default value

File: presentation/authentication/src/main/java/com/giraffe/authentication/login/screen/LoginScreen.kt [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+            when (effect) {
+                is LoginEffect.NavigateToWebViewScreen -> navigateToWebViewScreen()
+
+                is LoginEffect.NavigateToHomeScreen -> navigateToHomeScreen()
+
+                is LoginEffect.NavigateToResetPasswordScreen -> navigateToResetPasswordScreen()
+
+                is LoginEffect.PopBack -> popBack()
+
+                is LoginEffect.Error -> {}
```
Comment (Mohamed-Ashraf-2210) [inline presentation/authentication/src/main/java/com/giraffe/authentication/login/screen/LoginScreen.kt]: What is important this

**Review by Mohamed-Ashraf-2210 — CHANGES_REQUESTED** [review]

File: presentation/authentication/src/main/java/com/giraffe/authentication/login/screen/LoginScreen.kt (hunk 4 above)
Comment (Mostafa-khaled21) [reply presentation/authentication/src/main/java/com/giraffe/authentication/login/screen/LoginScreen.kt]: I think navigateBack or onBackClick

**Review by Mostafa-khaled21 — CHANGES_REQUESTED** [review]

**Review by Mostafa-khaled21 — APPROVED** [review]

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]
