### PR TITLE
Fix cast details crash

### LINKED ISSUE #447: Cast details: crash when click show more here
Image

### PR DESCRIPTION
**Pull request by HendSayed25**
- Fix LazyGrid crash due to reused key;
-  moved clickable modifier from Image to parent Box for better interaction

### CODE REVIEW

File: presentation/details/src/main/java/com/giraffe/details/components/TransitionBetweenColumnAndVerticalGrid.kt [hunk 1]
```diff
@@ -52,7 +52,7 @@ fun TransitionBetweenColumnAndVerticalGrid(
                     verticalArrangement = Arrangement.spacedBy(16.dp),
                     contentPadding = contentPadding
                 ) {
-                    items(items = poster, key = { poster -> poster.id }) { poster ->
```
Comment (mohamedebrahem13) [inline presentation/details/src/main/java/com/giraffe/details/components/TransitionBetweenColumnAndVerticalGrid.kt:55]: this key is important because it prevent unnecessary recompositing, are you sure this cause exception

**Review by mohamedebrahem13 — CHANGES_REQUESTED** [review]

File: presentation/details/src/main/java/com/giraffe/details/components/TransitionBetweenColumnAndVerticalGrid.kt (hunk 1 above)
Comment (skaik-mo) [reply presentation/details/src/main/java/com/giraffe/details/components/TransitionBetweenColumnAndVerticalGrid.kt:55]: The problem is a duplicate ID

Comment (HendSayed25) [reply presentation/details/src/main/java/com/giraffe/details/components/TransitionBetweenColumnAndVerticalGrid.kt:55]: yes , like skaik said 
there is a duplication in ID so I did this action here

Comment (mohamedebrahem13) [reply presentation/details/src/main/java/com/giraffe/details/components/TransitionBetweenColumnAndVerticalGrid.kt:55]: > yes , like skaik said there is a duplication in ID so I did this action here

removing the key does not solve the problem maybe we solve the duplicate id problem itself

**Review by mohamedebrahem13 — APPROVED** [review]

**Review by skaik-mo — APPROVED** [review]

**Review by mohannadahmed00 — APPROVED** [review]

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]
