### PR TITLE
fix issues in cast credit screen

### LINKED ISSUE #684: Cast Credit Screen

### PR DESCRIPTION
**Pull request by Mohamed-Ashraf-2210**
- show genres name
- show image
- navigate to another screen

### CODE REVIEW

File: presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditScreen.kt [hunk 1]
```diff
@@ -55,14 +55,36 @@ fun CastCreditScreen(
...
-    CastCreditContent(
-        state = state,
-        interaction = viewModel,
+    Box(
         modifier = Modifier
             .fillMaxSize()
             .background(Theme.color.background.screen)
             .systemBarsPadding()
-    )
+    ) {
```
Comment (dev-bilal-azzam) [inline presentation/details/src/main/java/com/giraffe/presentation/details/screens/castCredit/CastCreditScreen.kt]: why this we are already using BaseScreen to handle those states

**Review by dev-bilal-azzam — CHANGES_REQUESTED** [review]

**Review by dev-bilal-azzam — APPROVED** [review]

**Review by poula22 — APPROVED** [review]
