### PR TITLE
Fix/series details screen

### LINKED ISSUE #267: Fix animation in details screen
The placeholder should have the same size as the image.

https://github.com/user-attachments/assets/725d4418-692a-4890-8240-686b28a3cb2f

### LINKED ISSUE #271: Crash When Click on a Series Item
https://github.com/user-attachments/assets/46782785-efd2-444e-830f-e15f76570e70

### LINKED ISSUE #276: Fix series screen
https://github.com/user-attachments/assets/35829911-529d-4327-8ab1-5940bdd0f33e

### PR DESCRIPTION
**Pull request by Mohamed-Ashraf-2210**
Fix crash when click on a series item from explore screen
Fix animation in series details screen

https://github.com/user-attachments/assets/96fdafa9-fc45-494b-bfa5-1ee11261ce40

### CODE REVIEW

File: presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsInteractionListener.kt [hunk 1]
```diff
@@ -1,22 +1,11 @@
 package com.giraffe.details.screens.seriesdetails
 
 interface SeriesDetailsInteractionListener {
-    fun showMoreSeason()
-    fun showMoreCast()
-    fun showMoreRecommendedSeries()
     fun onClickGiveStars()
-    fun showMoreReviews()
```
Comment (HendSayed25) [inline presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsInteractionListener.kt:8]: why remove this action ? the screen has reviwes

File: presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/screen/SeriesDetailsScreen.kt [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+import com.giraffe.details.screens.seriesdetails.SeriesDetailsViewModel
+import com.giraffe.details.utils.EventListener
+import org.koin.androidx.compose.koinViewModel
+
+@Composable
+fun SeriesDetailsScreen(
+    navigateToRecommendedSeries: (seriesID: Int, titleSeries: String) -> Unit,
+    navigateToCastDetails: (castID: Int) -> Unit,
+    navigateToSeason: (seriesId: Int) -> Unit,
+    navigateToSeriesDetails: (seriesId: Int) -> Unit,
```
Comment (HendSayed25) [inline presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/screen/SeriesDetailsScreen.kt:27]: how navigate to series details  in series details screen??
where you use this action ?

File: presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsInteractionListener.kt [hunk 3]
```diff
@@ -1,22 +1,11 @@
 package com.giraffe.details.screens.seriesdetails
 
 interface SeriesDetailsInteractionListener {
-    fun showMoreSeason()
```
Comment (HendSayed25) [inline presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsInteractionListener.kt:4]: and this why delete all action of show more?

File: presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsViewModel.kt [hunk 4]
```diff
@@ -87,53 +94,34 @@ class SeriesDetailsViewModel(
...
-        sendEffect(SeriesDetailsEffect.Error(error))
-    }
-
 
     fun loadSeason(seriesId: Int) {
         safeExecute(
-            onSuccess = ::loadLastSeasonsSuccess,
-            onError = ::loadLastSeasonsError
+            onSuccess = ::loadSeasonsSuccess,
+            onError = ::loadError
```
Comment (HendSayed25) [inline presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsViewModel.kt:105]: where this function ? LoadError

File: presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/screen/SeriesDetailsScreen.kt (hunk 2 above)
Comment (Mohamed-Ashraf-2210) [reply presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/screen/SeriesDetailsScreen.kt:27]: when click in series from recommended list

File: presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsViewModel.kt (hunk 4 above)
Comment (Mohamed-Ashraf-2210) [reply presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsViewModel.kt:105]: in the same class

File: presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsInteractionListener.kt (hunk 3 above)
Comment (Mohamed-Ashraf-2210) [reply presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsInteractionListener.kt:4]: unused functoin

File: presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsInteractionListener.kt (hunk 1 above)
Comment (Mohamed-Ashraf-2210) [reply presentation/details/src/main/java/com/giraffe/details/screens/seriesdetails/SeriesDetailsInteractionListener.kt:8]: not used function and screen review want to refactor

**Review by HendSayed25 — DISMISSED** [review]

**Review by poula22 — DISMISSED** [review]

**Review by dev-bilal-azzam — DISMISSED** [review]

**Review by HendSayed25 — APPROVED** [review]

File: presentation/details/src/main/java/com/giraffe/details/components/MainMovieOrSeriesDetails.kt [hunk 5]
```diff
@@ -73,15 +72,15 @@ fun MainMovieOrSeriesDetails(
                 ) {
                     Icon(
                         painter = painterResource(Theme.icons.dueTone.image),
-                        contentDescription = "",
+                        contentDescription = null,
```
Comment (Mostafa-khaled21) [inline presentation/details/src/main/java/com/giraffe/details/components/MainMovieOrSeriesDetails.kt:75]: Avoid leaving the content description null

**Review by Mostafa-khaled21 — APPROVED** [review]

**Review by poula22 — APPROVED** [review]

**Review by dev-bilal-azzam — APPROVED** [review]
