### PR TITLE
Fix/Remote/Language

### LINKED ISSUE #376: Add interceptor for language to include current locale in request parameters
- Currently our `network` layer does not `automatically` send the user’s preferred `language` to the backend.

### PR DESCRIPTION
**Pull request by K-M-9**
- Add a `LanguageInterceptor` to automatically include the `current` language parameter when `fetching` data in `each` request.

### CODE REVIEW

File: app/src/main/java/com/giraffe/cineverseapp/data/network/CreateRetrofitClient.kt [hunk 1]
```diff
@@ -14,6 +16,7 @@ fun createRetrofitClient(accessToken: String): OkHttpClient {
     return OkHttpClient.Builder()
         .addInterceptor(AuthInterceptor(accessToken))
         .addInterceptor(loggingInterceptor)
+        .addInterceptor(LanguageInterceptor(Locale.getDefault().language))
```
Comment (poula22) [inline app/src/main/java/com/giraffe/cineverseapp/data/network/CreateRetrofitClient.kt]: Language may be change during send 2 requests, so don't include it in constructor. use value of  Locale.getDefault().language each time you send request in function.

**Review by dev-bilal-azzam — DISMISSED** [review]

**Review by poula22 — CHANGES_REQUESTED** [review]

**Review by mohannadahmed00 — APPROVED** [review]

**Review by poula22 — APPROVED** [review]
Great Job👏

**Review by HendSayed25 — APPROVED** [review]

**Review by doaaabdelnaser — APPROVED** [review]

**Review by HendSayed25 — APPROVED** [review]
