### PR TITLE
Fix/home animation

### LINKED ISSUE #350: Home: Screen Jumps Vertically While Scrolling Carousel
While scrolling horizontally within the carousel, the entire screen shifts up and down.

https://github.com/user-attachments/assets/82f6aad7-b053-45c9-9689-2c98364480f2

### PR DESCRIPTION
**Pull request by dev-bilal-azzam**

### CODE REVIEW

File: presentation/home/src/main/java/com/giraffe/home/components/MovieItem.kt [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+import com.giraffe.designsystem.composable.custom.Icon
+import com.giraffe.designsystem.composable.custom.Text
+import com.giraffe.designsystem.theme.CineVerseTheme
+import com.giraffe.designsystem.theme.Theme
+import com.giraffe.home.screen.home.MediaType
+import com.giraffe.home.screen.home.PopularMediaUiModel
+import com.giraffe.imageviewer.component.SafeIslamicImage
+
+@Composable
+fun MovieItem(
```
Comment (Mohamed-Ashraf-2210) [inline presentation/home/src/main/java/com/giraffe/home/components/MovieItem.kt]: why movie ?

**Review by Mohamed-Ashraf-2210 — DISMISSED** [review]

**Review by HendSayed25 — DISMISSED** [review]

File: presentation/home/src/main/java/com/giraffe/home/components/MovieItem.kt (hunk 1 above)
Comment (dev-bilal-azzam) [reply presentation/home/src/main/java/com/giraffe/home/components/MovieItem.kt]: It was called movie that's why I kept it movie.
I didn't realize that it is for movies and tv shows.

**Review by doaaabdelnaser — DISMISSED** [review]

**Review by Mohamed-Ashraf-2210 — DISMISSED** [review]

File: presentation/home/src/main/java/com/giraffe/home/components/VODItem.kt [hunk 2]
```diff
@@ -0,0 +1,136 @@
...
+import com.giraffe.designsystem.composable.custom.Icon
+import com.giraffe.designsystem.composable.custom.Text
+import com.giraffe.designsystem.theme.CineVerseTheme
+import com.giraffe.designsystem.theme.Theme
+import com.giraffe.home.screen.home.MediaType
+import com.giraffe.home.screen.home.PopularMediaUiModel
+import com.giraffe.imageviewer.component.SafeIslamicImage
+
+@Composable
+fun VODItem(
```
Comment (HendSayed25) [inline presentation/home/src/main/java/com/giraffe/home/components/VODItem.kt:31]: what is the meaning of VOD?

File: presentation/home/src/main/java/com/giraffe/home/components/VODItem.kt [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+    }
+}
+
+
+@Composable
+@Preview(
+    showBackground = true,
+    showSystemUi = false
+)
+private fun PreviewMovieItem() {
```
Comment (HendSayed25) [inline presentation/home/src/main/java/com/giraffe/home/components/VODItem.kt]: not forget to change the name of preview function like the name of composable

**Review by doaaabdelnaser — DISMISSED** [review]

File: presentation/home/src/main/java/com/giraffe/home/components/VODItem.kt (hunk 2 above)
Comment (dev-bilal-azzam) [reply presentation/home/src/main/java/com/giraffe/home/components/VODItem.kt:31]: video on demand. general name for movies and tv shows.
it is a service like netflix.

**Review by HendSayed25 — APPROVED** [review]

File: presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt [hunk 4]
```diff
@@ -53,86 +40,75 @@ fun Carousel(
...
-        state = pagerState,
-    ) { pageIndex ->
-        val isSelected = pageIndex == pagerState.currentPage
-        val zIndex = animateFloatAsState(
-            targetValue = if (isSelected) 1f else 0f,
-            label = "ZIndexAnimation"
-        ).value
+    val currentMovieCard = movieCards[pagerState.currentPage]
+    val screenWidthDp = LocalConfiguration.current.screenWidthDp.dp
+    val width = screenWidthDp - 48.dp
```
Comment (Mostafa-khaled21) [inline presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt:45]: Using a fixed DP subtraction (e.g., 48.dp) won't scale well across different screen sizes. This could break the layout proportions on small or large devices.

Comment (dev-bilal-azzam) [reply presentation/home/src/main/java/com/giraffe/home/components/Carousel.kt:45]: the 48.dp is the padding value so that it is fixed

**Review by Mostafa-khaled21 — APPROVED** [review]

**Review by Mohamed-Ashraf-2210 — APPROVED** [review]

**Review by Ashraf-El-Fallah — APPROVED** [review]
